FROM node:latest as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG CONFIG=qa
ARG BASE_URL=/
RUN npm run build -- --configuration=$CONFIG --base-href=$BASE_URL --deploy-url=$BASE_URL
# Stage 1: serve app with nginx server
FROM nginx:latest
COPY --from=build /app/dist/todo  /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080