export enum Folders {
    src = 'src',
    app = 'app',
    core = 'core',
    baseenums = 'base-enums',
    basemodels = 'base-models',
    basedataaccess = 'base-data-access',
    response = 'response',
    dataaccess = 'data-access',
    components = 'components',
    erros = 'erros',
    guards = 'guards',
    interceptors = 'interceptors',
    services = 'services',
    featuremodules = 'feature-modules',
    layouts = 'layouts',
    shared = 'shared',
    directives = 'directives',
    helpers = 'helpers',
    pipes = 'pipes',
    storage = 'storage',
    notification = 'notification',
    notificationlayout = 'notification-layout',
    icons = 'icons',
    images = 'images',
    logos = 'logos'
}
